Dockerfile

[Release notes](https://alpinelinux.org/posts/Alpine-3.13.0-released.html)

Update alpine from 3.12.3 to 3.13.0

---

Dockerfile
internal/pipeline/testdata/fetch

Update golang from 1.18.3 to 1.18.4

---

internal/filter/docker/docker.go

https://www.docker.com/blog/docker-hub-v1-api-deprecation/

docker: Switch to v2 API

---

Dockerfile

Update golang to 1.19.2 from 1.19.1

---

Dockerfile

Update golang to 1.19.4 from 1.19.3

---

Dockerfile
internal/filter/svn/svn.go

Update golang to 1.20.0 from 1.19.5

---

internal/pipeline/pipeline.go

Only show outputs instead of diffs, mostly confusing.

Simplify verbose pipeline output

---

Dockerfile

Update golang to 1.20.6 from 1.20.5

---

Dockerfile

[Release notes](https://alpinelinux.org/posts/Alpine-3.18.3-released.html)

Update alpine to 3.18.3 from 3.18.2

---

Dockerfile

Update golang to 1.21.0 from 1.20.7

---

Dockerfile

Update golang to 1.21.1 from 1.21.0

---

Dockerfile

Update golang to 1.21.3 from 1.21.2

---

Dockerfile

Update golang to 1.21.4 from 1.21.3

---

Dockerfile

Update golang to 1.22.6 from 1.22.5

---

Dockerfile

Update golang to 1.23.0 from 1.22.6

---

Dockerfile

Update golang to 1.23.1 from 1.23.0

---

Dockerfile

Update golang to 1.23.2 from 1.23.1

---

Dockerfile

Update golang to 1.23.3 from 1.23.2

---

Dockerfile

Update golang to 1.23.4 from 1.23.3

---

Dockerfile

[Release notes](https://alpinelinux.org/posts/Alpine-3.21.1-released.html)

Update alpine to 3.21.1 from 3.21.0

---

Dockerfile

[Release notes](https://alpinelinux.org/posts/Alpine-3.21.3-released.html)

Update alpine to 3.21.3 from 3.21.2

---

Dockerfile

Update golang to 1.24.5 from 1.24.4

---

Dockerfile

[Release notes](https://alpinelinux.org/posts/Alpine-3.22.1-released.html)

Update alpine to 3.22.1 from 3.22.0
